version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGODB_URL=mongodb://mongo:27017/go-auth
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: